const cfg=window.FENIX_SUPABASE;
const sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const MASTER_EMAIL='agenciafenixwarriors@gmail.com';
const view=document.getElementById('marketingView');
const title=document.getElementById('marketingTitle');
const userLabel=document.getElementById('userLabel');
const logoutBtn=document.getElementById('logoutBtn');
const toastEl=document.getElementById('toast');
let session=null;
let state={clients:[],campaigns:[],tasks:[],contents:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const isAdminRole=r=>['master','admin','adm'].includes(String(r||'').toLowerCase());
function toast(msg,type='info'){toastEl.textContent=msg;toastEl.dataset.type=type;toastEl.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toastEl.classList.remove('show'),3600)}
function setBusy(on){document.body.classList.toggle('loading',!!on);document.querySelectorAll('button,input,select').forEach(el=>el.disabled=!!on)}
function badge(s){return `<span class="badge">${esc(s)}</span>`}
async function getSession(){session=(await sb.auth.getSession()).data.session;return session}
async function callOrchestrator(payload){const s=await getSession();if(!s)throw new Error('Sessão expirada. Entre novamente.');const r=await fetch(`${cfg.url}/functions/v1/marketing-orchestrator`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`,'apikey':cfg.publishableKey},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||data.error||'Falha na automação.');return data}
function loginView(msg=''){title.textContent='Acesso seguro';userLabel.textContent='';logoutBtn.style.display='none';view.innerHTML=`<section class="panel login auth-card"><div class="auth-mark">🐦‍🔥</div><h2>FÊNIX Marketing AI</h2><p>Entre com uma conta administrativa autorizada.</p><div class="formgrid"><div class="wide"><label for="loginEmail">E-mail</label><input id="loginEmail" type="email" autocomplete="username" value="${esc(MASTER_EMAIL)}"></div><div class="wide"><label for="loginPassword">Senha</label><div class="password-wrap"><input id="loginPassword" type="password" autocomplete="current-password"><button type="button" class="icon-btn secondary" onclick="togglePassword('loginPassword',this)" aria-label="Mostrar ou ocultar senha">Mostrar</button></div></div></div><div class="actions auth-actions"><button onclick="login()">Entrar</button><button class="secondary" onclick="requestPasswordRecovery()">Esqueci minha senha</button></div><p class="mini">Usuário MASTER: ${esc(MASTER_EMAIL)}</p>${msg?`<p class="danger">${esc(msg)}</p>`:''}<p id="recoveryMsg" class="ok" aria-live="polite"></p></section>`;setTimeout(()=>document.getElementById('loginPassword')?.focus(),0)}
function togglePassword(id,btn){const el=document.getElementById(id);if(!el)return;el.type=el.type==='password'?'text':'password';btn.textContent=el.type==='password'?'Mostrar':'Ocultar'}
async function login(){const email=document.getElementById('loginEmail')?.value.trim();const password=document.getElementById('loginPassword')?.value||'';if(!email||!password)return toast('Informe e-mail e senha.','error');setBusy(true);const {data,error}=await sb.auth.signInWithPassword({email,password});setBusy(false);if(error)return loginView('Não foi possível entrar. Verifique e-mail e senha.');if(!isAdminRole(data.user?.app_metadata?.role)){await sb.auth.signOut();return loginView('Conta autenticada sem permissão administrativa.')}await boot()}
async function requestPasswordRecovery(){const email=(document.getElementById('loginEmail')?.value||MASTER_EMAIL).trim().toLowerCase();const msg=document.getElementById('recoveryMsg');if(msg)msg.textContent='Enviando link seguro...';const redirectTo=`${location.origin}${location.pathname}`;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo});if(error){if(msg){msg.className='danger';msg.textContent='Não foi possível enviar o link: '+error.message}return}if(msg){msg.className='ok';msg.textContent='Link enviado. Abra o e-mail e defina uma nova senha.'}}
function passwordChangeView(reason='Por segurança, crie uma nova senha antes de continuar.'){title.textContent='Nova senha';userLabel.textContent=session?.user?.email||'';logoutBtn.style.display='inline-block';logoutBtn.onclick=logout;view.innerHTML=`<section class="panel login auth-card"><div class="auth-mark">🔐</div><h2>Crie sua nova senha</h2><p>${esc(reason)}</p><div class="notice">Use pelo menos 10 caracteres, incluindo maiúscula, minúscula, número e um símbolo.</div><div class="formgrid" style="margin-top:16px"><div class="wide"><label for="newPassword">Nova senha</label><input id="newPassword" type="password" autocomplete="new-password" minlength="10"></div><div class="wide"><label for="confirmPassword">Confirmar nova senha</label><input id="confirmPassword" type="password" autocomplete="new-password" minlength="10"></div></div><div class="actions"><button onclick="saveNewPassword()">Salvar nova senha</button></div><p id="passwordChangeMsg" aria-live="polite"></p></section>`}
async function saveNewPassword(){const a=document.getElementById('newPassword')?.value||'';const b=document.getElementById('confirmPassword')?.value||'';const msg=document.getElementById('passwordChangeMsg');if(a.length<10||!/[A-Z]/.test(a)||!/[a-z]/.test(a)||!/[0-9]/.test(a)||!/[^A-Za-z0-9]/.test(a)){msg.className='danger';msg.textContent='A senha não atende aos requisitos.';return}if(a!==b){msg.className='danger';msg.textContent='As senhas não coincidem.';return}setBusy(true);const {error}=await sb.auth.updateUser({password:a});if(error){setBusy(false);msg.className='danger';msg.textContent='Não foi possível alterar a senha: '+error.message;return}const s=await getSession();try{const r=await fetch(`${cfg.url}/functions/v1/team-admin`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`,'apikey':cfg.publishableKey},body:JSON.stringify({action:'complete_password_change'})});if(!r.ok)throw new Error('Falha ao concluir primeiro acesso');await sb.auth.refreshSession()}catch(e){setBusy(false);msg.className='danger';msg.textContent='Senha alterada. Entre novamente para concluir o acesso.';return}setBusy(false);history.replaceState({},document.title,location.pathname);toast('Senha atualizada com sucesso.','success');await boot()}
async function logout(){await sb.auth.signOut();session=null;loginView('Sessão encerrada.')}
async function loadAll(){const [a,b,c,d]=await Promise.all([sb.from('marketing_clients').select('*').order('created_at',{ascending:false}),sb.from('marketing_campaigns').select('*,marketing_clients(name)').order('created_at',{ascending:false}),sb.from('marketing_tasks').select('*,marketing_campaigns(name)').order('created_at',{ascending:false}).limit(500),sb.from('content_items').select('id,title,objective,channel,format,hook,script,cta,campaign,scheduled_for,status,views,followers,leads,hosts,marketing_campaign_id').not('marketing_campaign_id','is',null).order('scheduled_for',{ascending:true}).limit(500)]);const err=a.error||b.error||c.error||d.error;if(err)throw err;state={clients:a.data||[],campaigns:b.data||[],tasks:c.data||[],contents:d.data||[]}}
function agents(){return [['Diretor de Marketing IA','Estratégia e orquestração'],['Social Media IA','Calendário e distribuição'],['Copywriter IA','Hooks, roteiros e CTAs'],['Designer IA','Briefings criativos'],['Vídeo IA','Roteiros e produção'],['CRM/Vendas IA','Funil e follow-up'],['Analista IA','Métricas e otimização'],['Compliance IA','Validação pré-publicação']]}
function dashboard(){title.textContent='Centro de Comando';const active=state.campaigns.filter(x=>x.status==='Ativa').length;const pending=state.tasks.filter(x=>['Pendente','Em execução','Aguardando aprovação','Aprovada'].includes(x.status)).length;const approval=state.tasks.filter(x=>x.status==='Aguardando aprovação').length;const done=state.tasks.filter(x=>x.status==='Concluída').length;view.innerHTML=`<div class="hero"><div><span class="eyebrow">CENTRO DE COMANDO</span><h2><span class="status-dot"></span>Marketing AI operacional</h2><p>Crie campanhas, acione os agentes e acompanhe execução, conteúdo e aprovações em um único painel.</p></div><button onclick="routeTo('campaigns')">+ Nova campanha</button></div><div class="grid metrics">${[['Clientes',state.clients.length],['Campanhas ativas',active],['Tarefas em fluxo',pending],['Aguardando aprovação',approval],['Concluídas',done],['Conteúdos',state.contents.length]].map(x=>`<div class="card metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><section class="panel"><div class="section-title"><h3>Esquadrão de agentes</h3><span class="pill">8 agentes</span></div><div class="agent-grid">${agents().map(a=>`<div class="agent"><b>${a[0]}</b><span>${a[1]}</span></div>`).join('')}</div></section><section class="panel"><div class="section-title"><h3>Campanhas recentes</h3><button class="secondary" onclick="routeTo('campaigns')">Ver todas</button></div>${state.campaigns.length?campaignTable(state.campaigns.slice(0,8)):'<div class="empty">Nenhuma campanha cadastrada.</div>'}</section>`}
function clients(){title.textContent='Clientes';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Novo cliente</h3><span class="pill">Workspace</span></div><div class="formgrid"><div><label>Nome</label><input id="clientName"></div><div><label>Segmento</label><input id="clientSegment"></div><div class="wide"><label>Público principal</label><input id="clientAudience"></div><div class="wide"><label>Oferta principal</label><input id="clientOffer"></div><div><label>Tom de voz</label><select id="clientTone"><option>Profissional</option><option>Premium</option><option>Direto</option><option>Educativo</option><option>Inspirador</option></select></div><div><label>Canais</label><input id="clientChannels" value="Instagram,TikTok,WhatsApp"></div></div><div class="actions"><button onclick="createClient()">Cadastrar cliente</button></div></section><section class="panel"><h3>Clientes</h3>${state.clients.length?`<div class="table-wrap"><table><thead><tr><th>Nome</th><th>Segmento</th><th>Público</th><th>Canais</th><th>Status</th></tr></thead><tbody>${state.clients.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.segment)}</td><td>${esc(c.audience)}</td><td>${esc((c.channels||[]).join(', '))}</td><td>${badge(c.status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Cadastre o primeiro cliente.</div>'}</section>`}
async function createClient(){const name=document.getElementById('clientName')?.value.trim();if(!name)return toast('Informe o nome do cliente.','error');setBusy(true);const channels=document.getElementById('clientChannels').value.split(',').map(x=>x.trim()).filter(Boolean);const {error}=await sb.from('marketing_clients').insert({name,segment:clientSegment.value.trim(),audience:clientAudience.value.trim(),offer:clientOffer.value.trim(),tone:clientTone.value,channels,created_by:session.user.id});setBusy(false);if(error)return toast('Erro: '+error.message,'error');await refresh('clients');toast('Cliente cadastrado.','success')}
function campaignTable(list){return `<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Campanha</th><th>Objetivo</th><th>Autonomia</th><th>Status</th><th>Ação</th></tr></thead><tbody>${list.map(c=>`<tr><td>${esc(c.marketing_clients?.name||'')}</td><td><b>${esc(c.name)}</b></td><td>${esc(c.objective)}</td><td>${badge(c.autonomy)}</td><td>${badge(c.status)}</td><td><div class="task-actions"><button onclick="planCampaign('${c.id}')">Executar IA</button><button class="secondary" onclick="showStrategy('${c.id}')">Estratégia</button></div></td></tr>`).join('')}</tbody></table></div>`}
function campaigns(){title.textContent='Campanhas';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Nova campanha</h3><span class="pill">Orquestração automática</span></div>${state.clients.length?`<div class="formgrid"><div><label>Cliente</label><select id="campaignClient">${state.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div><label>Nome</label><input id="campaignName"></div><div class="wide"><label>Objetivo</label><input id="campaignObjective"></div><div><label>Meta</label><input id="campaignTarget" type="number" min="0" value="100"></div><div><label>Unidade</label><select id="campaignUnit"><option>leads</option><option>vendas</option><option>seguidores</option><option>inscrições</option><option>agendamentos</option></select></div><div><label>Autonomia</label><select id="campaignAutonomy"><option>Assistido</option><option>Manual</option><option>Autônomo</option></select></div><div><label>Data final</label><input id="campaignEnd" type="date"></div></div><div class="actions"><button onclick="createCampaign()">Criar e executar</button></div>`:'<div class="empty">Cadastre um cliente antes de criar campanhas.</div>'}</section><section class="panel"><h3>Campanhas</h3>${state.campaigns.length?campaignTable(state.campaigns):'<div class="empty">Nenhuma campanha.</div>'}</section><section id="strategyPanel" class="panel" hidden></section>`}
async function createCampaign(){if(!campaignName.value.trim()||!campaignObjective.value.trim())return toast('Informe nome e objetivo.','error');setBusy(true);const payload={client_id:campaignClient.value,name:campaignName.value.trim(),objective:campaignObjective.value.trim(),target_value:+campaignTarget.value||0,target_unit:campaignUnit.value,autonomy:campaignAutonomy.value,end_date:campaignEnd.value||null,created_by:session.user.id};const {data,error}=await sb.from('marketing_campaigns').insert(payload).select('id').single();if(error){setBusy(false);return toast('Erro: '+error.message,'error')}try{const r=await callOrchestrator({action:'plan_campaign',campaign_id:data.id});toast(`Campanha criada: ${r.tasks} tarefas e ${r.contents} conteúdos.`, 'success')}catch(e){toast('Campanha criada, mas a automação falhou: '+e.message,'error')}setBusy(false);await refresh('campaigns')}
async function planCampaign(id){setBusy(true);try{const r=await callOrchestrator({action:'plan_campaign',campaign_id:id});toast(`Automação concluída: ${r.tasks} tarefas e ${r.contents} conteúdos.`, 'success')}catch(e){toast(e.message,'error')}setBusy(false);await refresh('campaigns')}
function showStrategy(id){const c=state.campaigns.find(x=>x.id===id);const p=document.getElementById('strategyPanel');if(!p)return;const s=c?.strategy||{};p.hidden=false;p.innerHTML=`<div class="section-title"><h3>Estratégia — ${esc(c?.name||'')}</h3><button class="secondary" onclick="this.closest('.panel').hidden=true">Fechar</button></div><div class="strategy"><div><strong>Posicionamento</strong>${esc(s.positioning||'Execute a IA para gerar.')}</div><div><strong>Público</strong>${esc(s.audience||'—')}</div><div><strong>Oferta</strong>${esc(s.offer||'—')}</div><div><strong>Canais</strong>${esc(s.channels||'—')}</div><div><strong>Cadência</strong>${esc(s.cadence||'—')}</div><div><strong>Meta</strong>${esc(s.target||'—')}</div></div>`;p.scrollIntoView({behavior:'smooth',block:'start'})}
function tasks(){title.textContent='Agentes & Tarefas';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Fila dos agentes</h3><div class="toolbar"><select id="taskFilter" onchange="renderTaskTable()"><option>Todas</option><option>Pendente</option><option>Aguardando aprovação</option><option>Aprovada</option><option>Concluída</option><option>Erro</option></select><button class="secondary" onclick="completeApprovedAll()">Concluir aprovadas</button></div></div><div id="taskTable"></div></section>`;renderTaskTable()}
function renderTaskTable(){const f=document.getElementById('taskFilter')?.value||'Todas';const rows=state.tasks.filter(t=>f==='Todas'||t.status===f);document.getElementById('taskTable').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Campanha</th><th>Agente</th><th>Tarefa</th><th>Status</th><th>Prazo</th><th>Ações</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(t.marketing_campaigns?.name||'')}</td><td>${esc(t.agent)}</td><td><b>${esc(t.title)}</b><br><span class="mini">${esc(t.description)}</span></td><td>${badge(t.status)}</td><td>${fmtDate(t.due_at)}</td><td><div class="task-actions">${t.status==='Aguardando aprovação'?`<button onclick="approveTask('${t.id}')">Aprovar</button>`:''}${!['Concluída','Erro'].includes(t.status)?`<button class="secondary" onclick="advanceTask('${t.id}')">Executar</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma tarefa neste filtro.</div>'}
async function approveTask(id){setBusy(true);try{await callOrchestrator({action:'approve_task',task_id:id});toast('Tarefa aprovada.','success')}catch(e){toast(e.message,'error')}setBusy(false);await refresh('tasks')}
async function advanceTask(id){setBusy(true);try{const r=await callOrchestrator({action:'advance_task',task_id:id});toast('Status: '+r.task.status,'success')}catch(e){toast(e.message,'error')}setBusy(false);await refresh('tasks')}
async function completeApprovedAll(){const ids=[...new Set(state.tasks.filter(t=>t.status==='Aprovada').map(t=>t.campaign_id))];if(!ids.length)return toast('Não há tarefas aprovadas.');setBusy(true);let total=0;for(const id of ids){try{const r=await callOrchestrator({action:'complete_approved',campaign_id:id});total+=r.completed||0}catch(e){console.error(e)}}setBusy(false);toast(`${total} tarefa(s) concluída(s).`,'success');await refresh('tasks')}
function content(){title.textContent='Conteúdo';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Conteúdo gerado</h3><span class="pill">${state.contents.length} itens</span></div>${state.contents.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Título</th><th>Canal</th><th>Formato</th><th>Objetivo</th><th>Status</th><th>CTA</th></tr></thead><tbody>${state.contents.map(c=>`<tr><td>${fmtDate(c.scheduled_for)}</td><td><b>${esc(c.title)}</b><br><span class="mini">${esc(c.hook||'')}</span></td><td>${esc(c.channel)}</td><td>${esc(c.format)}</td><td>${esc(c.objective)}</td><td>${badge(c.status)}</td><td>${esc(c.cta||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Execute uma campanha para gerar conteúdo.</div>'}</section>`}
const routes={dashboard,clients,campaigns,tasks,content};
function routeTo(name){document.querySelectorAll('#marketingNav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));routes[name]?.()}
async function refresh(route='dashboard'){try{await loadAll();routeTo(route)}catch(e){toast('Falha ao carregar dados: '+e.message,'error')}}
async function boot(){const s=await getSession();if(!s)return loginView();if(!isAdminRole(s.user?.app_metadata?.role)){await sb.auth.signOut();return loginView('Conta sem permissão administrativa.')}session=s;userLabel.textContent=s.user.email||'';logoutBtn.style.display='inline-block';logoutBtn.onclick=logout;const recovery=location.hash.includes('type=recovery')||new URLSearchParams(location.search).get('type')==='recovery';if(recovery||s.user?.app_metadata?.must_change_password===true)return passwordChangeView(recovery?'Defina uma nova senha para recuperar o acesso.':'Esta conta exige troca de senha no primeiro acesso.');try{await loadAll();routeTo('dashboard')}catch(e){view.innerHTML=`<section class="panel"><h3>Não foi possível abrir o Marketing AI</h3><p>${esc(e.message)}</p><button onclick="boot()">Tentar novamente</button></section>`}}
document.querySelectorAll('#marketingNav [data-view]').forEach(b=>b.addEventListener('click',()=>routeTo(b.dataset.view)));
sb.auth.onAuthStateChange((event,newSession)=>{if(event==='PASSWORD_RECOVERY'){session=newSession;setTimeout(()=>passwordChangeView('Defina uma nova senha para recuperar o acesso.'),0)}});
boot();