const cfg=window.FENIX_SUPABASE;
const sb=window.supabase.createClient(cfg.url,cfg.publishableKey);
const view=document.getElementById('marketingView');
const title=document.getElementById('marketingTitle');
const userLabel=document.getElementById('userLabel');
const logoutBtn=document.getElementById('logoutBtn');
const toastEl=document.getElementById('toast');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
let session=null;
let state={clients:[],campaigns:[],tasks:[],contents:[]};
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),3200)}
function setBusy(on){document.body.classList.toggle('loading',!!on)}
function badge(s){return `<span class="badge">${esc(s)}</span>`}
async function getSession(){session=(await sb.auth.getSession()).data.session;return session}
async function callOrchestrator(payload){const s=await getSession();if(!s)throw new Error('Sessão expirada.');const r=await fetch(`${cfg.url}/functions/v1/marketing-orchestrator`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`,'apikey':cfg.publishableKey},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||data.error||'Falha na automação.');return data}
function loginView(msg=''){title.textContent='Acesso';userLabel.textContent='';logoutBtn.style.display='none';view.innerHTML=`<section class="panel login"><h2>FÊNIX Marketing AI</h2><p>Entre com uma conta administrativa autorizada.</p><div class="formgrid"><div class="wide"><label>E-mail</label><input id="loginEmail" type="email" autocomplete="username"></div><div class="wide"><label>Senha</label><input id="loginPassword" type="password" autocomplete="current-password"></div></div><div class="actions"><button onclick="login()">Entrar</button></div><p class="danger">${esc(msg)}</p></section>`}
async function login(){setBusy(true);const {data,error}=await sb.auth.signInWithPassword({email:loginEmail.value.trim(),password:loginPassword.value});setBusy(false);if(error)return loginView('Não foi possível entrar. Verifique os dados.');const role=data.user?.app_metadata?.role;if(!['master','admin','adm','MASTER','ADMIN','ADM'].includes(role)){await sb.auth.signOut();return loginView('Conta autenticada sem permissão administrativa.')}await boot()}
async function logout(){await sb.auth.signOut();loginView('Sessão encerrada.')}
async function loadAll(){const [a,b,c,d]=await Promise.all([
  sb.from('marketing_clients').select('*').order('created_at',{ascending:false}),
  sb.from('marketing_campaigns').select('*,marketing_clients(name)').order('created_at',{ascending:false}),
  sb.from('marketing_tasks').select('*,marketing_campaigns(name)').order('created_at',{ascending:false}).limit(500),
  sb.from('content_items').select('id,title,objective,channel,format,hook,script,cta,campaign,scheduled_for,status,views,followers,leads,hosts,marketing_campaign_id').not('marketing_campaign_id','is',null).order('scheduled_for',{ascending:true}).limit(500)
]);
  const err=a.error||b.error||c.error||d.error;if(err)throw err;state={clients:a.data||[],campaigns:b.data||[],tasks:c.data||[],contents:d.data||[]};
}
function agents(){return [
  ['Diretor de Marketing IA','Estratégia, prioridade e orquestração'],['Social Media IA','Calendário e distribuição editorial'],['Copywriter IA','Hooks, roteiros, legendas e CTAs'],['Designer IA','Briefings e formatos criativos'],['Vídeo IA','Roteiros curtos e produção'],['CRM/Vendas IA','Funil e follow-up de leads'],['Analista IA','Métricas e otimização'],['Compliance IA','Validação antes da publicação']
]}
function dashboard(){title.textContent='Centro de Comando';const active=state.campaigns.filter(x=>x.status==='Ativa').length;const pending=state.tasks.filter(x=>['Pendente','Em execução','Aguardando aprovação','Aprovada'].includes(x.status)).length;const approval=state.tasks.filter(x=>x.status==='Aguardando aprovação').length;const done=state.tasks.filter(x=>x.status==='Concluída').length;view.innerHTML=`<div class="hero"><h2><span class="status-dot"></span>FÊNIX Marketing AI operacional</h2><p>Cadastre clientes, crie campanhas e acione o Diretor de Marketing IA. O sistema gera estratégia, tarefas por agente e conteúdo vinculado à campanha, com aprovação conforme o nível de autonomia.</p></div><div class="grid">${[['Clientes',state.clients.length],['Campanhas ativas',active],['Tarefas em fluxo',pending],['Aguardando aprovação',approval],['Concluídas',done],['Conteúdos gerados',state.contents.length]].map(x=>`<div class="card metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><section class="panel"><div class="section-title"><h3>Esquadrão de agentes</h3><span class="pill">8 agentes</span></div><div class="agent-grid" style="margin-top:14px">${agents().map(a=>`<div class="agent"><b>${a[0]}</b><span>${a[1]}</span></div>`).join('')}</div></section><section class="panel"><div class="section-title"><h3>Campanhas recentes</h3><button onclick="routeTo('campaigns')">Nova campanha</button></div>${state.campaigns.length?`<table><thead><tr><th>Cliente</th><th>Campanha</th><th>Objetivo</th><th>Autonomia</th><th>Status</th><th>Ação</th></tr></thead><tbody>${state.campaigns.slice(0,8).map(c=>campaignRow(c)).join('')}</tbody></table>`:'<div class="empty">Nenhuma campanha cadastrada.</div>'}</section>`}
function clients(){title.textContent='Clientes';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Novo cliente</h3><span class="pill">Workspace isolado</span></div><div class="formgrid" style="margin-top:14px"><div><label>Nome da empresa/projeto</label><input id="clientName"></div><div><label>Segmento</label><input id="clientSegment" placeholder="Ex.: agência de streamers"></div><div class="wide"><label>Público principal</label><input id="clientAudience" placeholder="Quem queremos atingir?"></div><div class="wide"><label>Oferta principal</label><input id="clientOffer" placeholder="Produto, serviço ou ação desejada"></div><div><label>Tom de voz</label><select id="clientTone"><option>Profissional</option><option>Premium</option><option>Direto</option><option>Educativo</option><option>Inspirador</option></select></div><div><label>Canais</label><input id="clientChannels" value="Instagram,TikTok,WhatsApp" placeholder="Separados por vírgula"></div></div><div class="actions"><button onclick="createClient()">Cadastrar cliente</button></div></section><section class="panel"><h3>Clientes</h3>${state.clients.length?`<table><thead><tr><th>Nome</th><th>Segmento</th><th>Público</th><th>Canais</th><th>Status</th></tr></thead><tbody>${state.clients.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.segment)}</td><td>${esc(c.audience)}</td><td>${esc((c.channels||[]).join(', '))}</td><td>${badge(c.status)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Cadastre o primeiro cliente.</div>'}</section>`}
async function createClient(){const name=clientName.value.trim();if(!name)return toast('Informe o nome do cliente.');setBusy(true);const channels=clientChannels.value.split(',').map(x=>x.trim()).filter(Boolean);const {error}=await sb.from('marketing_clients').insert({name,segment:clientSegment.value.trim(),audience:clientAudience.value.trim(),offer:clientOffer.value.trim(),tone:clientTone.value,channels,created_by:session.user.id});setBusy(false);if(error)return toast('Erro: '+error.message);await refresh('clients');toast('Cliente cadastrado.')}
function campaignRow(c){return `<tr><td>${esc(c.marketing_clients?.name||'')}</td><td><b>${esc(c.name)}</b></td><td>${esc(c.objective)}</td><td>${badge(c.autonomy)}</td><td>${badge(c.status)}</td><td><div class="task-actions"><button onclick="planCampaign('${c.id}')">Executar IA</button><button class="secondary" onclick="showStrategy('${c.id}')">Estratégia</button></div></td></tr>`}
function campaigns(){title.textContent='Campanhas';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Nova campanha</h3><span class="pill">Orquestração automática</span></div>${state.clients.length?`<div class="formgrid" style="margin-top:14px"><div><label>Cliente</label><select id="campaignClient">${state.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div><label>Nome da campanha</label><input id="campaignName" placeholder="Ex.: Captação Setembro"></div><div class="wide"><label>Objetivo</label><input id="campaignObjective" placeholder="Ex.: captar novos interessados qualificados"></div><div><label>Meta numérica</label><input id="campaignTarget" type="number" min="0" value="100"></div><div><label>Unidade</label><select id="campaignUnit"><option>leads</option><option>vendas</option><option>seguidores</option><option>inscrições</option><option>agendamentos</option></select></div><div><label>Autonomia</label><select id="campaignAutonomy"><option>Assistido</option><option>Manual</option><option>Autônomo</option></select></div><div><label>Data final</label><input id="campaignEnd" type="date"></div></div><div class="actions"><button onclick="createCampaign()">Criar e executar campanha</button></div>`:'<div class="empty">Cadastre um cliente antes de criar campanhas.</div>'}</section><section class="panel"><h3>Campanhas</h3>${state.campaigns.length?`<table><thead><tr><th>Cliente</th><th>Campanha</th><th>Objetivo</th><th>Autonomia</th><th>Status</th><th>Ação</th></tr></thead><tbody>${state.campaigns.map(c=>campaignRow(c)).join('')}</tbody></table>`:'<div class="empty">Nenhuma campanha.</div>'}</section><section id="strategyPanel" class="panel" style="display:none"></section>`}
async function createCampaign(){if(!campaignName.value.trim()||!campaignObjective.value.trim())return toast('Informe nome e objetivo.');setBusy(true);const payload={client_id:campaignClient.value,name:campaignName.value.trim(),objective:campaignObjective.value.trim(),target_value:+campaignTarget.value||0,target_unit:campaignUnit.value,autonomy:campaignAutonomy.value,end_date:campaignEnd.value||null,created_by:session.user.id};const {data,error}=await sb.from('marketing_campaigns').insert(payload).select('id').single();if(error){setBusy(false);return toast('Erro: '+error.message)}try{await callOrchestrator({action:'plan_campaign',campaign_id:data.id});toast('Campanha planejada e agentes acionados.')}catch(e){toast('Campanha criada; automação: '+e.message)}setBusy(false);await refresh('campaigns')}
async function planCampaign(id){setBusy(true);try{const r=await callOrchestrator({action:'plan_campaign',campaign_id:id});toast(`Automação concluída: ${r.tasks} tarefas e ${r.contents} conteúdos.`)}catch(e){toast(e.message)}setBusy(false);await refresh('campaigns')}
function showStrategy(id){const c=state.campaigns.find(x=>x.id===id);const p=document.getElementById('strategyPanel');if(!p)return;const s=c?.strategy||{};p.style.display='block';p.innerHTML=`<div class="section-title"><h3>Estratégia — ${esc(c?.name||'')}</h3><button class="secondary" onclick="this.closest('.panel').style.display='none'">Fechar</button></div><div class="strategy" style="margin-top:14px"><div><strong>Posicionamento</strong>${esc(s.positioning||'Execute a IA para gerar.')}</div><div><strong>Público</strong>${esc(s.audience||'—')}</div><div><strong>Oferta</strong>${esc(s.offer||'—')}</div><div><strong>Canais</strong>${esc(s.channels||'—')}</div><div><strong>Cadência</strong>${esc(s.cadence||'—')}</div><div><strong>Meta</strong>${esc(s.target||'—')}</div></div>`;p.scrollIntoView({behavior:'smooth',block:'start'})}
function tasks(){title.textContent='Agentes & Tarefas';const filters=['Todas','Pendente','Aguardando aprovação','Aprovada','Concluída','Erro'];view.innerHTML=`<section class="panel"><div class="section-title"><h3>Fila dos agentes</h3><div class="toolbar"><select id="taskFilter" onchange="renderTaskTable()" style="min-width:190px">${filters.map(x=>`<option>${x}</option>`).join('')}</select><button class="secondary" onclick="completeApprovedAll()">Concluir aprovadas</button></div></div><div id="taskTable"></div></section>`;renderTaskTable()}
function renderTaskTable(){const f=document.getElementById('taskFilter')?.value||'Todas';const rows=state.tasks.filter(t=>f==='Todas'||t.status===f);document.getElementById('taskTable').innerHTML=rows.length?`<table><thead><tr><th>Campanha</th><th>Agente</th><th>Tarefa</th><th>Status</th><th>Prazo</th><th>Ações</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(t.marketing_campaigns?.name||'')}</td><td>${esc(t.agent)}</td><td><b>${esc(t.title)}</b><br><span class="mini">${esc(t.description)}</span></td><td>${badge(t.status)}</td><td>${fmtDate(t.due_at)}</td><td><div class="task-actions">${t.status==='Aguardando aprovação'?`<button onclick="approveTask('${t.id}')">Aprovar</button>`:''}${!['Concluída','Erro'].includes(t.status)?`<button class="secondary" onclick="advanceTask('${t.id}')">Executar</button>`:''}</div></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma tarefa neste filtro.</div>'}
async function approveTask(id){setBusy(true);try{await callOrchestrator({action:'approve_task',task_id:id});toast('Tarefa aprovada.')}catch(e){toast(e.message)}setBusy(false);await refresh('tasks')}
async function advanceTask(id){setBusy(true);try{const r=await callOrchestrator({action:'advance_task',task_id:id});toast('Status: '+r.task.status)}catch(e){toast(e.message)}setBusy(false);await refresh('tasks')}
async function completeApprovedAll(){const ids=[...new Set(state.tasks.filter(t=>t.status==='Aprovada').map(t=>t.campaign_id))];if(!ids.length)return toast('Não há tarefas aprovadas.');setBusy(true);let total=0;for(const id of ids){try{const r=await callOrchestrator({action:'complete_approved',campaign_id:id});total+=r.completed||0}catch(e){console.error(e)}}setBusy(false);toast(`${total} tarefa(s) concluída(s).`);await refresh('tasks')}
function content(){title.textContent='Conteúdo';view.innerHTML=`<section class="panel"><div class="section-title"><h3>Conteúdo gerado pelas campanhas</h3><span class="pill">${state.contents.length} itens</span></div>${state.contents.length?`<table><thead><tr><th>Data</th><th>Título</th><th>Canal</th><th>Formato</th><th>Objetivo</th><th>Status</th><th>CTA</th></tr></thead><tbody>${state.contents.map(c=>`<tr><td>${fmtDate(c.scheduled_for)}</td><td><b>${esc(c.title)}</b><br><span class="mini">${esc(c.hook||'')}</span></td><td>${esc(c.channel)}</td><td>${esc(c.format)}</td><td>${esc(c.objective)}</td><td>${badge(c.status)}</td><td>${esc(c.cta||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Execute uma campanha para gerar conteúdo.</div>'}</section>`}
const routes={dashboard,clients,campaigns,tasks,content};
function routeTo(name){document.querySelectorAll('#marketingNav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));routes[name]?.()}
async function refresh(route='dashboard'){try{await loadAll();routeTo(route)}catch(e){toast('Falha ao carregar dados: '+e.message)}}
async function boot(){const s=await getSession();if(!s)return loginView();const role=s.user?.app_metadata?.role;if(!['master','admin','adm','MASTER','ADMIN','ADM'].includes(role)){await sb.auth.signOut();return loginView('Conta sem permissão administrativa.')}session=s;userLabel.textContent=s.user.email||'';logoutBtn.style.display='inline-block';logoutBtn.onclick=logout;try{await loadAll();routeTo('dashboard')}catch(e){view.innerHTML=`<section class="panel"><h3>Não foi possível abrir o Marketing AI</h3><p>${esc(e.message)}</p></section>`}}
document.querySelectorAll('#marketingNav button[data-view]').forEach(b=>b.onclick=()=>routeTo(b.dataset.view));boot();